plugins {
    id 'com.android.application'
}

android {
    namespace 'com.realtimebus.web'
    compileSdk 34
    def releaseKeystore = file('../realtime-bus.keystore')

    defaultConfig {
        applicationId "com.realtimebus.web"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    signingConfigs {
        release {
            if (releaseKeystore.exists()) {
                storeFile releaseKeystore
                storePassword 'android'
                keyAlias 'realtimebus'
                keyPassword 'android'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            signingConfig releaseKeystore.exists() ? signingConfigs.release : signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }
}

dependencies {
    implementation 'org.nanohttpd:nanohttpd:2.3.1'
}
